version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb+srv://vsing4753:KrR7tHeaw8yTFqKB@cluster0.vsuwcf2.mongodb.net
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    # Add other configurations as needed
